data:
  dataset: plant_leaves
  base_file_path: ./data/
  local_file: reduced_leaves_dataset
  local_file_augmented: augmented_leaves_dataset
  chunking_size: 100
  image_height: 150
  image_width: 200
  grey_threshold: 10
  crop_side: 10
  crop_top_bottom: 25

training_parameters:
  leaves: mango, jamun, jatropha, pomegranate, chinar
  train_test_split: 0.3
  cuda_device: cpu
  learning_rate: 0.001
  l2_regularization: 0.001
  epochs: 1000
  early_stopping: 25
  batch_size: 50
  dropout: 0.3


